config/routes.rb
Cartoque::Application.routes.draw do
  # Authentication routes
  devise_for :users

  # API
  namespace :api, defaults: { format: 'json' } do
    resources :contacts
    resources :apps
    resources :servers
    resources :users do
      collection { get :random_token, as: :random_token }
    end
    resources :locations
    resources :operating_systems
    get "history", to: "history#index", as: "history"
    #hook for generators
    root 'root#index'
    #catch-all route to avoid ActionController#RoutingError's
    match '*a', to: 'application#render_404', via: :all
  end

  # Webapp
  resources :contacts
  resources :apps
  resources :servers
  resources :users
  resources :locations
  resources :operating_systems
  get "help/:page", to: "help#show", as: "help"
  get "welcome/index"

  # Default root
  root 'welcome#index'

  # Catch-all route to avoid ActionController#RoutingError's
  match '*a', to: 'application#render_404', via: :all

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/server.rb
class Server < ActiveRecord::Base
  # audit for changes
  has_paper_trail
end

app/controllers/api/servers_controller.rb
class API::ServersController < API::ApplicationController
  # GET /api/servers
  def index
    respond_with Server.page(params[:page]).per_page(items_per_page)
  end

  # GET /api/servers/1
  def show
    respond_with Server.find(params[:id])
  end

  # POST /api/servers
  def create
    server = Server.new(server_params)
    if server.save
      respond_with server
    else
      render_error json: { message: "Validation Failed", errors: server.errors }
    end
  end

  # PATCH/PUT /api/servers/1
  def update
    server = Server.find(params[:id])
    if server.update(server_params)
      respond_with server
    else
      render_error json: { message: "Validation Failed", errors: server.errors }
    end
  end

  # DELETE /api/servers/1
  def destroy
    respond_with Server.destroy(params[:id])
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def server_params
    params.require(:server).permit(:name)
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.order(:name).page(params[:page]).per_page(50)
    respond_with @servers
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    respond_with @server
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render action: 'show', status: :created, location: @server }
      else
        format.html { render action: 'new' }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name)
    end
end

app/views/servers/_form.html.erb
<%= form_for(@server, html: { class: "form-horizontal" }) do |f| %>

  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>
      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class=form-group>
    <%= f.label :name, class: "col-sm-1 control-label" %>
    <div class=col-sm-4>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class=form-group>
    <div class="col-sm-offset-1 col-sm-6">
      <%= f.button type: "submit", class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/servers/edit.html.erb
<h1><%= link_to "Servers", servers_path %></h1>

<div class=show>
  <div class=pull-right>
    <%= link_to 'Show', @server %>
  </div>
  <h2><%= @server.name %></h2>
  <%= render 'form' %>
</div>

app/views/servers/index.html.erb
<h1>Servers</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan=2 class=action-buttons>
        <%= link_to 'New Server', new_server_path, id: 'new' %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= link_to server.name, server %></td>
        <td class=action-buttons><%= link_to 'Edit', edit_server_path(server), class: 'edit' %></td>
        <td class=action-buttons><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @servers, previous_label: h("<"), next_label: h(">") %>

app/views/servers/new.html.erb
<h1><%= link_to "Servers", servers_path %></h1>

<div class=show>
  <h2>New server</h2>
  <%= render 'form' %>
</div>

app/views/servers/show.html.erb
<h1><%= link_to "Servers", servers_path %></h1>

<div class=show>
  <div class=pull-right>
    <%= link_to 'Edit', edit_server_path(@server), id: 'edit' %>
  </div>
  <h2><%= @server.name %></h2>
</div>