config/routes.rb
Cartoque::Application.routes.draw do
  # Authentication routes
  devise_for :users

  # API
  namespace :api, defaults: { format: 'json' } do
    resources :contacts
    resources :apps
    resources :servers
    resources :users do
      collection { get :random_token, as: :random_token }
    end
    resources :locations
    resources :operating_systems
    get "history", to: "history#index", as: "history"
    #hook for generators
    root 'root#index'
    #catch-all route to avoid ActionController#RoutingError's
    match '*a', to: 'application#render_404', via: :all
  end

  # Webapp
  resources :contacts
  resources :apps
  resources :servers
  resources :users
  resources :locations
  resources :operating_systems
  get "help/:page", to: "help#show", as: "help"
  get "welcome/index"

  # Default root
  root 'welcome#index'

  # Catch-all route to avoid ActionController#RoutingError's
  match '*a', to: 'application#render_404', via: :all

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # audit for changes
  has_paper_trail
end

app/controllers/api/contacts_controller.rb
class API::ContactsController < API::ApplicationController
  # GET /api/contacts
  def index
    respond_with Contact.page(params[:page]).per_page(items_per_page)
  end

  # GET /api/contacts/1
  def show
    respond_with Contact.find(params[:id])
  end

  # POST /api/contacts
  def create
    contact = Contact.new(contact_params)
    if contact.save
      respond_with contact
    else
      render_error json: { message: "Validation Failed", errors: contact.errors }
    end
  end

  # PATCH/PUT /api/contacts/1
  def update
    contact = Contact.find(params[:id])
    if contact.update(contact_params)
      respond_with contact
    else
      render_error json: { message: "Validation Failed", errors: contact.errors }
    end
  end

  # DELETE /api/contacts/1
  def destroy
    respond_with Contact.destroy(params[:id])
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per_page(50)
    respond_with @contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    respond_with @contact
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name)
    end
end

app/views/contacts/_form.html.erb
<%= form_for(@contact, html: { class: "form-horizontal" }) do |f| %>

  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>
      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class=form-group>
    <%= f.label :name, class: "col-sm-1 control-label" %>
    <div class=col-sm-4>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class=form-group>
    <div class="col-sm-offset-1 col-sm-6">
      <%= f.button type: "submit", class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/contacts/edit.html.erb
<h1><%= link_to "Contacts", contacts_path %></h1>

<div class=show>
  <div class=pull-right>
    <%= link_to 'Show', @contact %>
  </div>
  <h2><%= @contact.name %></h2>
  <%= render 'form' %>
</div>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan=2 class=action-buttons>
        <%= link_to 'New Contact', new_contact_path, id: 'new' %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.name, contact %></td>
        <td class=action-buttons><%= link_to 'Edit', edit_contact_path(contact), class: 'edit' %></td>
        <td class=action-buttons><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @contacts, previous_label: h("<"), next_label: h(">") %>

app/views/contacts/new.html.erb
<h1><%= link_to "Contacts", contacts_path %></h1>

<div class=show>
  <h2>New contact</h2>
  <%= render 'form' %>
</div>

app/views/contacts/show.html.erb
<h1><%= link_to "Contacts", contacts_path %></h1>

<div class=show>
  <div class=pull-right>
    <%= link_to 'Edit', edit_contact_path(@contact), id: 'edit' %>
  </div>
  <h2><%= @contact.name %></h2>
</div>