config/routes.rb
Cartoque::Application.routes.draw do
  # Authentication routes
  devise_for :users

  # API
  namespace :api, defaults: { format: 'json' } do
    resources :contacts
    resources :apps
    resources :servers
    resources :users do
      collection { get :random_token, as: :random_token }
    end
    resources :locations
    resources :operating_systems
    get "history", to: "history#index", as: "history"
    #hook for generators
    root 'root#index'
    #catch-all route to avoid ActionController#RoutingError's
    match '*a', to: 'application#render_404', via: :all
  end

  # Webapp
  resources :contacts
  resources :apps
  resources :servers
  resources :users
  resources :locations
  resources :operating_systems
  get "help/:page", to: "help#show", as: "help"
  get "welcome/index"

  # Default root
  root 'welcome#index'

  # Catch-all route to avoid ActionController#RoutingError's
  match '*a', to: 'application#render_404', via: :all

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/apps/_form.html.erb
<%= form_for(@app, html: { class: "form-horizontal" }) do |f| %>

  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>
      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class=form-group>
    <%= f.label :name, class: "col-sm-1 control-label" %>
    <div class=col-sm-4>
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class=form-group>
    <div class="col-sm-offset-1 col-sm-6">
      <%= f.button type: "submit", class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/apps/edit.html.erb
<h1><%= link_to "Applications", apps_path %></h1>

<div class=show>
  <div class=pull-right>
    <%= link_to 'Show', @app %>
  </div>
  <h2><%= @app.name %></h2>
  <%= render 'form' %>
</div>

app/views/apps/index.html.erb
<h1>Applications</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan=2 class=action-buttons>
        <%= link_to 'New Application', new_app_path, id: 'new' %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= link_to app.name, app %></td>
        <td class=action-buttons><%= link_to 'Edit', edit_app_path(app), class: 'edit' %></td>
        <td class=action-buttons><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @apps, previous_label: h("<"), next_label: h(">") %>

app/views/apps/new.html.erb
<h1><%= link_to "Applications", apps_path %></h1>

<div class=show>
  <h2>New application</h2>
  <%= render 'form' %>
</div>

app/views/apps/show.html.erb
<h1><%= link_to "Applications", apps_path %></h1>

<div class=show>
  <div class=pull-right>
    <%= link_to 'Edit', edit_app_path(@app), id: 'edit' %>
  </div>
  <h2><%= @app.name %></h2>
</div>