config/routes.rb
Cartoque::Application.routes.draw do
  # Authentication routes
  devise_for :users

  # API
  namespace :api, defaults: { format: 'json' } do
    resources :contacts
    resources :apps
    resources :servers
    resources :users do
      collection { get :random_token, as: :random_token }
    end
    resources :locations
    resources :operating_systems
    get "history", to: "history#index", as: "history"
    #hook for generators
    root 'root#index'
    #catch-all route to avoid ActionController#RoutingError's
    match '*a', to: 'application#render_404', via: :all
  end

  # Webapp
  resources :contacts
  resources :apps
  resources :servers
  resources :users
  resources :locations
  resources :operating_systems
  get "help/:page", to: "help#show", as: "help"
  get "welcome/index"

  # Default root
  root 'welcome#index'

  # Catch-all route to avoid ActionController#RoutingError's
  match '*a', to: 'application#render_404', via: :all

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_navbar.html.erb
<div class="main-navbar navbar navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Cartoque', root_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse">
      <ul class="nav navbar-nav">
      <% if signed_in? %>
        <li><%= link_to 'Applications', apps_path %></li>
        <li><%= link_to 'Servers', servers_path %></li>
        <li><%= link_to 'Contacts', contacts_path %></li>
      <% end %>
      </ul>
      <% if signed_in? %>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to content_tag(:i, '', class: 'fa fa-cog'), users_path %></li>
      </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar_settings.html.erb
<ul class="nav nav-tabs nav-settings">
  <% {
        "Users"      => users_path,
        "Locations"  => locations_path,
        "Operating Systems" => operating_systems_path
     }.each do |title, path| %>
    <%= content_tag :li, link_to(title, path), class: (active.to_s == title.downcase ? "active" : nil) %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cartoque</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class=page-wrap>

  <%= render 'layouts/navbar' %>

  <div class=container id=container>
    <%= content_tag :div, id: "flash" do %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "flash-#{name}" %>
      <% end %>
    <% end unless flash.empty? %>
    <%= yield %>
  </div>

</div>

<div class=site-footer>
  <% if signed_in? %>
  <div class=container>
    <div class=row>
      <div class="col-md-4 text-left">
        <%= link_to content_tag(:i, "", class: "fa fa-keyboard-o")+" Keyboard shortcuts", help_path(page: "keyboard"),
                    remote: true  %>
      </div>
      <div class="col-md-4 text-center">
        <%= link_to "Cartoque v#{Cartoque::Application::VERSION}", "http://cartoque.org/" %>
      </div>
      <div class="col-md-4 text-right">
        <%= link_to content_tag(:i, "", class: "fa fa-sign-out")+" Log out", destroy_user_session_path, method: :delete %>
      </div>
  </div>
  <% end %>
</div>

</body>
</html>